// Package stamp writes .mbt/buildstamp.h, the build provenance header.
//
// A banner that names its build ("UFSD 1.4.0 (a5c7b82)") needs the commit at
// compile time.  As a -D flag the value would be baked into an object that is
// recompiled only when its source changes, so a build after a commit would
// still carry the previous hash (mbt#59).  As a header it is tracked like any
// other include, and because it is rewritten only when its content changes, an
// unchanged commit recompiles nothing.
//
// The text is identical to mbt v2's (scripts/mbt/buildstamp.py), so objects
// that include it are byte-identical between the two.
package stamp

import (
	"bytes"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
)

// Path is where the header lives, relative to the project root.
const Path = ".mbt/buildstamp.h"

// Resolve returns the short commit of the checkout at dir and whether its
// tracked files are modified.  Outside a git checkout it returns "unknown".
// Untracked files do not count: stray notes are no provenance difference.
func Resolve(dir string) (commit string, dirty bool) {
	out, err := git(dir, "rev-parse", "--short", "HEAD")
	if err != nil || out == "" {
		return "unknown", false
	}
	st, err := git(dir, "status", "--porcelain", "--untracked-files=no")
	if err != nil {
		return out, false
	}
	return out, st != ""
}

func git(dir string, args ...string) (string, error) {
	cmd := exec.Command("git", args...)
	cmd.Dir = dir
	out, err := cmd.Output()
	return strings.TrimSpace(string(out)), err
}

func cString(s string) string {
	s = strings.ReplaceAll(s, `\`, `\\`)
	s = strings.ReplaceAll(s, `"`, `\"`)
	return `"` + s + `"`
}

// Render returns the header text.
func Render(project, version, commit string, dirty bool) string {
	stamp := commit
	d := 0
	if dirty {
		stamp += "-dirty"
		d = 1
	}
	return fmt.Sprintf(`/* buildstamp.h -- auto-generated by mbt.  Do not edit, do not commit.
 *
 * Build provenance for this project.  On the include path as <buildstamp.h>
 * (mk/mbt.mk adds -I .mbt), so a banner can carry the exact build it is:
 *
 *     #include <buildstamp.h>
 *     printf("%%s %%s (%%s)\n", MBT_PROJECT, MBT_VERSION, MBT_COMMIT);
 *
 * Regenerated at every `+"`make`"+`, but rewritten only when a value actually
 * changed -- an unchanged commit recompiles nothing.  Carries no build
 * timestamp on purpose: that would differ every run.
 */
#ifndef MBT_BUILDSTAMP_H
#define MBT_BUILDSTAMP_H

#define MBT_PROJECT      %s
#define MBT_VERSION      %s

/* Short commit of the project checkout, with a "-dirty" suffix when the tree
 * has uncommitted *tracked* changes; "unknown" outside a git checkout.
 * MBT_COMMIT_DIRTY is the same signal as 0/1 for code that reports it
 * separately (a warning line rather than a suffix). */
#define MBT_COMMIT       %s
#define MBT_COMMIT_DIRTY %d

#endif /* MBT_BUILDSTAMP_H */
`, cString(project), cString(version), cString(stamp), d)
}

// Write renders the header for the project at root and writes it only when the
// content differs.  It reports whether the file was written.
func Write(root, project, version string) (bool, error) {
	commit, dirty := Resolve(root)
	content := []byte(Render(project, version, commit, dirty))
	p := filepath.Join(root, Path)
	if old, err := os.ReadFile(p); err == nil && bytes.Equal(old, content) {
		return false, nil
	}
	if err := os.MkdirAll(filepath.Dir(p), 0o755); err != nil {
		return false, err
	}
	return true, os.WriteFile(p, content, 0o644)
}
