/* buildstamp.h -- auto-generated by mbt.  Do not edit, do not commit.
 *
 * Build provenance for this project.  On the include path as <buildstamp.h>
 * (mk/mbt.mk adds -I .mbt), so a banner can carry the exact build it is:
 *
 *     #include <buildstamp.h>
 *     printf("%s %s (%s)\n", MBT_PROJECT, MBT_VERSION, MBT_COMMIT);
 *
 * Regenerated at every `make`, but rewritten only when a value actually
 * changed -- an unchanged commit recompiles nothing.  Carries no build
 * timestamp on purpose: that would differ every run.
 */
#ifndef MBT_BUILDSTAMP_H
#define MBT_BUILDSTAMP_H

#define MBT_PROJECT      "my \"q\" proj"
#define MBT_VERSION      "1.0.0"

/* Short commit of the project checkout, with a "-dirty" suffix when the tree
 * has uncommitted *tracked* changes; "unknown" outside a git checkout.
 * MBT_COMMIT_DIRTY is the same signal as 0/1 for code that reports it
 * separately (a warning line rather than a suffix). */
#define MBT_COMMIT       "abc1234-dirty"
#define MBT_COMMIT_DIRTY 1

#endif /* MBT_BUILDSTAMP_H */
